//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace TTC2019.LiveContest.Metamodels.Bibtex
{
    
    
    /// <summary>
    /// The public interface for DatedEntry
    /// </summary>
    [DefaultImplementationTypeAttribute(typeof(DatedEntry))]
    [XmlDefaultImplementationTypeAttribute(typeof(DatedEntry))]
    [ModelRepresentationClassAttribute("https://www.transformation-tool-contest.eu/2019/bibtex#//DatedEntry")]
    public interface IDatedEntry : IModelElement, IBibTeXEntry
    {
        
        /// <summary>
        /// The year property
        /// </summary>
        [DisplayNameAttribute("year")]
        [CategoryAttribute("DatedEntry")]
        [XmlElementNameAttribute("year")]
        [XmlAttributeAttribute(true)]
        int Year
        {
            get;
            set;
        }
        
        /// <summary>
        /// Gets fired before the Year property changes its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> YearChanging;
        
        /// <summary>
        /// Gets fired when the Year property changed its value
        /// </summary>
        event System.EventHandler<ValueChangedEventArgs> YearChanged;
    }
}

