//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace TTC2019.LiveContest.Metamodels.Bibtex
{
    
    
    /// <summary>
    /// The default implementation of the InBook class
    /// </summary>
    [XmlNamespaceAttribute("https://www.transformation-tool-contest.eu/2019/bibtex")]
    [XmlNamespacePrefixAttribute("bib")]
    [ModelRepresentationClassAttribute("https://www.transformation-tool-contest.eu/2019/bibtex#//InBook")]
    public partial class InBook : Book, IInBook, IModelElement
    {
        
        /// <summary>
        /// The backing field for the Chapter property
        /// </summary>
        private int _chapter;
        
        private static Lazy<ITypedElement> _chapterAttribute = new Lazy<ITypedElement>(RetrieveChapterAttribute);
        
        private static IClass _classInstance;
        
        /// <summary>
        /// The chapter property
        /// </summary>
        [DisplayNameAttribute("chapter")]
        [CategoryAttribute("InBook")]
        [XmlElementNameAttribute("chapter")]
        [XmlAttributeAttribute(true)]
        public int Chapter
        {
            get
            {
                return this._chapter;
            }
            set
            {
                if ((this._chapter != value))
                {
                    int old = this._chapter;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnChapterChanging(e);
                    this.OnPropertyChanging("Chapter", e, _chapterAttribute);
                    this._chapter = value;
                    this.OnChapterChanged(e);
                    this.OnPropertyChanged("Chapter", e, _chapterAttribute);
                }
            }
        }
        
        /// <summary>
        /// Gets the Class model for this type
        /// </summary>
        public new static IClass ClassInstance
        {
            get
            {
                if ((_classInstance == null))
                {
                    _classInstance = ((IClass)(MetaRepository.Instance.Resolve("https://www.transformation-tool-contest.eu/2019/bibtex#//InBook")));
                }
                return _classInstance;
            }
        }
        
        /// <summary>
        /// Gets fired before the Chapter property changes its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> ChapterChanging;
        
        /// <summary>
        /// Gets fired when the Chapter property changed its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> ChapterChanged;
        
        private static ITypedElement RetrieveChapterAttribute()
        {
            return ((ITypedElement)(((ModelElement)(InBook.ClassInstance)).Resolve("chapter")));
        }
        
        /// <summary>
        /// Raises the ChapterChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnChapterChanging(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.ChapterChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the ChapterChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnChapterChanged(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.ChapterChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Resolves the given attribute name
        /// </summary>
        /// <returns>The attribute value or null if it could not be found</returns>
        /// <param name="attribute">The requested attribute name</param>
        /// <param name="index">The index of this attribute</param>
        protected override object GetAttributeValue(string attribute, int index)
        {
            if ((attribute == "CHAPTER"))
            {
                return this.Chapter;
            }
            return base.GetAttributeValue(attribute, index);
        }
        
        /// <summary>
        /// Sets a value to the given feature
        /// </summary>
        /// <param name="feature">The requested feature</param>
        /// <param name="value">The value that should be set to that feature</param>
        protected override void SetFeature(string feature, object value)
        {
            if ((feature == "CHAPTER"))
            {
                this.Chapter = ((int)(value));
                return;
            }
            base.SetFeature(feature, value);
        }
        
        /// <summary>
        /// Gets the property expression for the given attribute
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="attribute">The requested attribute in upper case</param>
        protected override NMF.Expressions.INotifyExpression<object> GetExpressionForAttribute(string attribute)
        {
            if ((attribute == "CHAPTER"))
            {
                return Observable.Box(new ChapterProxy(this));
            }
            return base.GetExpressionForAttribute(attribute);
        }
        
        /// <summary>
        /// Gets the Class for this model element
        /// </summary>
        public override IClass GetClass()
        {
            if ((_classInstance == null))
            {
                _classInstance = ((IClass)(MetaRepository.Instance.Resolve("https://www.transformation-tool-contest.eu/2019/bibtex#//InBook")));
            }
            return _classInstance;
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the chapter property
        /// </summary>
        private sealed class ChapterProxy : ModelPropertyChange<IInBook, int>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public ChapterProxy(IInBook modelElement) : 
                    base(modelElement, "chapter")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override int Value
            {
                get
                {
                    return this.ModelElement.Chapter;
                }
                set
                {
                    this.ModelElement.Chapter = value;
                }
            }
        }
    }
}

