//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace TTC2019.LiveContest.Metamodels.Bibtex
{
    
    
    /// <summary>
    /// The default implementation of the ThesisEntry class
    /// </summary>
    [XmlNamespaceAttribute("https://www.transformation-tool-contest.eu/2019/bibtex")]
    [XmlNamespacePrefixAttribute("bib")]
    [ModelRepresentationClassAttribute("https://www.transformation-tool-contest.eu/2019/bibtex#//ThesisEntry")]
    public abstract partial class ThesisEntry : AuthoredEntry, IThesisEntry, IModelElement
    {
        
        /// <summary>
        /// The backing field for the School property
        /// </summary>
        private string _school;
        
        private static Lazy<ITypedElement> _schoolAttribute = new Lazy<ITypedElement>(RetrieveSchoolAttribute);
        
        /// <summary>
        /// The backing field for the Year property
        /// </summary>
        private int _year;
        
        private static Lazy<ITypedElement> _yearAttribute = new Lazy<ITypedElement>(RetrieveYearAttribute);
        
        /// <summary>
        /// The backing field for the Title property
        /// </summary>
        private string _title;
        
        private static Lazy<ITypedElement> _titleAttribute = new Lazy<ITypedElement>(RetrieveTitleAttribute);
        
        private static IClass _classInstance;
        
        /// <summary>
        /// The school property
        /// </summary>
        [DisplayNameAttribute("school")]
        [CategoryAttribute("ThesisEntry")]
        [XmlElementNameAttribute("school")]
        [XmlAttributeAttribute(true)]
        public string School
        {
            get
            {
                return this._school;
            }
            set
            {
                if ((this._school != value))
                {
                    string old = this._school;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnSchoolChanging(e);
                    this.OnPropertyChanging("School", e, _schoolAttribute);
                    this._school = value;
                    this.OnSchoolChanged(e);
                    this.OnPropertyChanged("School", e, _schoolAttribute);
                }
            }
        }
        
        /// <summary>
        /// The year property
        /// </summary>
        [DisplayNameAttribute("year")]
        [CategoryAttribute("DatedEntry")]
        [XmlElementNameAttribute("year")]
        [XmlAttributeAttribute(true)]
        public int Year
        {
            get
            {
                return this._year;
            }
            set
            {
                if ((this._year != value))
                {
                    int old = this._year;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnYearChanging(e);
                    this.OnPropertyChanging("Year", e, _yearAttribute);
                    this._year = value;
                    this.OnYearChanged(e);
                    this.OnPropertyChanged("Year", e, _yearAttribute);
                }
            }
        }
        
        /// <summary>
        /// The title property
        /// </summary>
        [DisplayNameAttribute("title")]
        [CategoryAttribute("TitledEntry")]
        [XmlElementNameAttribute("title")]
        [XmlAttributeAttribute(true)]
        public string Title
        {
            get
            {
                return this._title;
            }
            set
            {
                if ((this._title != value))
                {
                    string old = this._title;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnTitleChanging(e);
                    this.OnPropertyChanging("Title", e, _titleAttribute);
                    this._title = value;
                    this.OnTitleChanged(e);
                    this.OnPropertyChanged("Title", e, _titleAttribute);
                }
            }
        }
        
        /// <summary>
        /// Gets the child model elements of this model element
        /// </summary>
        public override IEnumerableExpression<IModelElement> Children
        {
            get
            {
                return base.Children.Concat(new ThesisEntryChildrenCollection(this));
            }
        }
        
        /// <summary>
        /// Gets the Class model for this type
        /// </summary>
        public new static IClass ClassInstance
        {
            get
            {
                if ((_classInstance == null))
                {
                    _classInstance = ((IClass)(MetaRepository.Instance.Resolve("https://www.transformation-tool-contest.eu/2019/bibtex#//ThesisEntry")));
                }
                return _classInstance;
            }
        }
        
        /// <summary>
        /// Gets fired before the School property changes its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> SchoolChanging;
        
        /// <summary>
        /// Gets fired when the School property changed its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> SchoolChanged;
        
        /// <summary>
        /// Gets fired before the Year property changes its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> YearChanging;
        
        /// <summary>
        /// Gets fired when the Year property changed its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> YearChanged;
        
        /// <summary>
        /// Gets fired before the Title property changes its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> TitleChanging;
        
        /// <summary>
        /// Gets fired when the Title property changed its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> TitleChanged;
        
        private static ITypedElement RetrieveSchoolAttribute()
        {
            return ((ITypedElement)(((ModelElement)(ThesisEntry.ClassInstance)).Resolve("school")));
        }
        
        /// <summary>
        /// Raises the SchoolChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnSchoolChanging(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.SchoolChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the SchoolChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnSchoolChanged(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.SchoolChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        private static ITypedElement RetrieveYearAttribute()
        {
            return ((ITypedElement)(((ModelElement)(DatedEntry.ClassInstance)).Resolve("year")));
        }
        
        /// <summary>
        /// Raises the YearChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnYearChanging(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.YearChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the YearChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnYearChanged(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.YearChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        private static ITypedElement RetrieveTitleAttribute()
        {
            return ((ITypedElement)(((ModelElement)(TitledEntry.ClassInstance)).Resolve("title")));
        }
        
        /// <summary>
        /// Raises the TitleChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnTitleChanging(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.TitleChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the TitleChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnTitleChanged(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.TitleChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Resolves the given attribute name
        /// </summary>
        /// <returns>The attribute value or null if it could not be found</returns>
        /// <param name="attribute">The requested attribute name</param>
        /// <param name="index">The index of this attribute</param>
        protected override object GetAttributeValue(string attribute, int index)
        {
            if ((attribute == "SCHOOL"))
            {
                return this.School;
            }
            if ((attribute == "YEAR"))
            {
                return this.Year;
            }
            if ((attribute == "TITLE"))
            {
                return this.Title;
            }
            return base.GetAttributeValue(attribute, index);
        }
        
        /// <summary>
        /// Sets a value to the given feature
        /// </summary>
        /// <param name="feature">The requested feature</param>
        /// <param name="value">The value that should be set to that feature</param>
        protected override void SetFeature(string feature, object value)
        {
            if ((feature == "SCHOOL"))
            {
                this.School = ((string)(value));
                return;
            }
            if ((feature == "YEAR"))
            {
                this.Year = ((int)(value));
                return;
            }
            if ((feature == "TITLE"))
            {
                this.Title = ((string)(value));
                return;
            }
            base.SetFeature(feature, value);
        }
        
        /// <summary>
        /// Gets the property expression for the given attribute
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="attribute">The requested attribute in upper case</param>
        protected override NMF.Expressions.INotifyExpression<object> GetExpressionForAttribute(string attribute)
        {
            if ((attribute == "SCHOOL"))
            {
                return new SchoolProxy(this);
            }
            if ((attribute == "YEAR"))
            {
                return Observable.Box(new YearProxy(this));
            }
            if ((attribute == "TITLE"))
            {
                return new TitleProxy(this);
            }
            return base.GetExpressionForAttribute(attribute);
        }
        
        /// <summary>
        /// Gets the Class for this model element
        /// </summary>
        public override IClass GetClass()
        {
            if ((_classInstance == null))
            {
                _classInstance = ((IClass)(MetaRepository.Instance.Resolve("https://www.transformation-tool-contest.eu/2019/bibtex#//ThesisEntry")));
            }
            return _classInstance;
        }
        
        /// <summary>
        /// The collection class to to represent the children of the ThesisEntry class
        /// </summary>
        public class ThesisEntryChildrenCollection : ReferenceCollection, ICollectionExpression<IModelElement>, ICollection<IModelElement>
        {
            
            private ThesisEntry _parent;
            
            /// <summary>
            /// Creates a new instance
            /// </summary>
            public ThesisEntryChildrenCollection(ThesisEntry parent)
            {
                this._parent = parent;
            }
            
            /// <summary>
            /// Gets the amount of elements contained in this collection
            /// </summary>
            public override int Count
            {
                get
                {
                    int count = 0;
                    return count;
                }
            }
            
            protected override void AttachCore()
            {
            }
            
            protected override void DetachCore()
            {
            }
            
            /// <summary>
            /// Adds the given element to the collection
            /// </summary>
            /// <param name="item">The item to add</param>
            public override void Add(IModelElement item)
            {
            }
            
            /// <summary>
            /// Clears the collection and resets all references that implement it.
            /// </summary>
            public override void Clear()
            {
            }
            
            /// <summary>
            /// Gets a value indicating whether the given element is contained in the collection
            /// </summary>
            /// <returns>True, if it is contained, otherwise False</returns>
            /// <param name="item">The item that should be looked out for</param>
            public override bool Contains(IModelElement item)
            {
                return false;
            }
            
            /// <summary>
            /// Copies the contents of the collection to the given array starting from the given array index
            /// </summary>
            /// <param name="array">The array in which the elements should be copied</param>
            /// <param name="arrayIndex">The starting index</param>
            public override void CopyTo(IModelElement[] array, int arrayIndex)
            {
            }
            
            /// <summary>
            /// Removes the given item from the collection
            /// </summary>
            /// <returns>True, if the item was removed, otherwise False</returns>
            /// <param name="item">The item that should be removed</param>
            public override bool Remove(IModelElement item)
            {
                return false;
            }
            
            /// <summary>
            /// Gets an enumerator that enumerates the collection
            /// </summary>
            /// <returns>A generic enumerator</returns>
            public override IEnumerator<IModelElement> GetEnumerator()
            {
                return Enumerable.Empty<IModelElement>().GetEnumerator();
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the school property
        /// </summary>
        private sealed class SchoolProxy : ModelPropertyChange<IThesisEntry, string>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public SchoolProxy(IThesisEntry modelElement) : 
                    base(modelElement, "school")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override string Value
            {
                get
                {
                    return this.ModelElement.School;
                }
                set
                {
                    this.ModelElement.School = value;
                }
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the year property
        /// </summary>
        private sealed class YearProxy : ModelPropertyChange<IDatedEntry, int>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public YearProxy(IDatedEntry modelElement) : 
                    base(modelElement, "year")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override int Value
            {
                get
                {
                    return this.ModelElement.Year;
                }
                set
                {
                    this.ModelElement.Year = value;
                }
            }
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the title property
        /// </summary>
        private sealed class TitleProxy : ModelPropertyChange<ITitledEntry, string>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public TitleProxy(ITitledEntry modelElement) : 
                    base(modelElement, "title")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override string Value
            {
                get
                {
                    return this.ModelElement.Title;
                }
                set
                {
                    this.ModelElement.Title = value;
                }
            }
        }
    }
}

