//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using NMF.Collections.Generic;
using NMF.Collections.ObjectModel;
using NMF.Expressions;
using NMF.Expressions.Linq;
using NMF.Models;
using NMF.Models.Collections;
using NMF.Models.Expressions;
using NMF.Models.Meta;
using NMF.Models.Repository;
using NMF.Serialization;
using NMF.Utilities;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;

namespace TTC2019.LiveContest.Metamodels.Bibtex
{
    
    
    /// <summary>
    /// The default implementation of the TitledEntry class
    /// </summary>
    [XmlNamespaceAttribute("https://www.transformation-tool-contest.eu/2019/bibtex")]
    [XmlNamespacePrefixAttribute("bib")]
    [ModelRepresentationClassAttribute("https://www.transformation-tool-contest.eu/2019/bibtex#//TitledEntry")]
    public abstract partial class TitledEntry : BibTeXEntry, ITitledEntry, IModelElement
    {
        
        /// <summary>
        /// The backing field for the Title property
        /// </summary>
        private string _title;
        
        private static Lazy<ITypedElement> _titleAttribute = new Lazy<ITypedElement>(RetrieveTitleAttribute);
        
        private static IClass _classInstance;
        
        /// <summary>
        /// The title property
        /// </summary>
        [DisplayNameAttribute("title")]
        [CategoryAttribute("TitledEntry")]
        [XmlElementNameAttribute("title")]
        [XmlAttributeAttribute(true)]
        public string Title
        {
            get
            {
                return this._title;
            }
            set
            {
                if ((this._title != value))
                {
                    string old = this._title;
                    ValueChangedEventArgs e = new ValueChangedEventArgs(old, value);
                    this.OnTitleChanging(e);
                    this.OnPropertyChanging("Title", e, _titleAttribute);
                    this._title = value;
                    this.OnTitleChanged(e);
                    this.OnPropertyChanged("Title", e, _titleAttribute);
                }
            }
        }
        
        /// <summary>
        /// Gets the Class model for this type
        /// </summary>
        public new static IClass ClassInstance
        {
            get
            {
                if ((_classInstance == null))
                {
                    _classInstance = ((IClass)(MetaRepository.Instance.Resolve("https://www.transformation-tool-contest.eu/2019/bibtex#//TitledEntry")));
                }
                return _classInstance;
            }
        }
        
        /// <summary>
        /// Gets fired before the Title property changes its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> TitleChanging;
        
        /// <summary>
        /// Gets fired when the Title property changed its value
        /// </summary>
        public event System.EventHandler<ValueChangedEventArgs> TitleChanged;
        
        private static ITypedElement RetrieveTitleAttribute()
        {
            return ((ITypedElement)(((ModelElement)(TitledEntry.ClassInstance)).Resolve("title")));
        }
        
        /// <summary>
        /// Raises the TitleChanging event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnTitleChanging(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.TitleChanging;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Raises the TitleChanged event
        /// </summary>
        /// <param name="eventArgs">The event data</param>
        protected virtual void OnTitleChanged(ValueChangedEventArgs eventArgs)
        {
            System.EventHandler<ValueChangedEventArgs> handler = this.TitleChanged;
            if ((handler != null))
            {
                handler.Invoke(this, eventArgs);
            }
        }
        
        /// <summary>
        /// Resolves the given attribute name
        /// </summary>
        /// <returns>The attribute value or null if it could not be found</returns>
        /// <param name="attribute">The requested attribute name</param>
        /// <param name="index">The index of this attribute</param>
        protected override object GetAttributeValue(string attribute, int index)
        {
            if ((attribute == "TITLE"))
            {
                return this.Title;
            }
            return base.GetAttributeValue(attribute, index);
        }
        
        /// <summary>
        /// Sets a value to the given feature
        /// </summary>
        /// <param name="feature">The requested feature</param>
        /// <param name="value">The value that should be set to that feature</param>
        protected override void SetFeature(string feature, object value)
        {
            if ((feature == "TITLE"))
            {
                this.Title = ((string)(value));
                return;
            }
            base.SetFeature(feature, value);
        }
        
        /// <summary>
        /// Gets the property expression for the given attribute
        /// </summary>
        /// <returns>An incremental property expression</returns>
        /// <param name="attribute">The requested attribute in upper case</param>
        protected override NMF.Expressions.INotifyExpression<object> GetExpressionForAttribute(string attribute)
        {
            if ((attribute == "TITLE"))
            {
                return new TitleProxy(this);
            }
            return base.GetExpressionForAttribute(attribute);
        }
        
        /// <summary>
        /// Gets the Class for this model element
        /// </summary>
        public override IClass GetClass()
        {
            if ((_classInstance == null))
            {
                _classInstance = ((IClass)(MetaRepository.Instance.Resolve("https://www.transformation-tool-contest.eu/2019/bibtex#//TitledEntry")));
            }
            return _classInstance;
        }
        
        /// <summary>
        /// Represents a proxy to represent an incremental access to the title property
        /// </summary>
        private sealed class TitleProxy : ModelPropertyChange<ITitledEntry, string>
        {
            
            /// <summary>
            /// Creates a new observable property access proxy
            /// </summary>
            /// <param name="modelElement">The model instance element for which to create the property access proxy</param>
            public TitleProxy(ITitledEntry modelElement) : 
                    base(modelElement, "title")
            {
            }
            
            /// <summary>
            /// Gets or sets the value of this expression
            /// </summary>
            public override string Value
            {
                get
                {
                    return this.ModelElement.Title;
                }
                set
                {
                    this.ModelElement.Title = value;
                }
            }
        }
    }
}

